import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import { BookOpenIcon, BookmarkAltIcon } from "@heroicons/react/outline";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-4xl lg:text-5xl xl:text-6xl text-center font-bold mb-4">
          Perpustakaan Kepak{" "}
          <a
            href="/"
            className="text-blue-400 hover:text-blue-500 focus:text-blue-600 hover:underline"
          >
            Sayap Suci
          </a>
        </h1>

        <p className={styles.description}>
          Get started by editing from{" "}
          <code className={styles.code}>/dashboard</code>
        </p>

        <div className="flex">
          <BookmarkAltIcon className="h-20 w-20 text-gray-600" />
          <BookOpenIcon className="h-20 w-20 text-gray-600" />
          <BookmarkAltIcon className="h-20 w-20 text-gray-600" />
        </div>

        <div className="md:flex">
          <Link href="/login">
            <div className="border p-8 w-56 md:w-80 rounded-lg hover:border-blue-400 hover:text-blue-400 m-2 cursor-pointer">
              <h2 className="text-2xl font-bold flex justify-center items-center">
                Login &rarr;
              </h2>
            </div>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;
